##--------------------------------------------------------------------
## rmqtt-acl
##--------------------------------------------------------------------

#Disconnect if publishing is rejected
disconnect_if_pub_rejected = true

rules = [
    ["allow", { user = "dashboard" }, "subscribe", ["$SYS/#"]],            # 允许用户名为dashboard的客户端订阅"$SYS/#"主题
    ["allow", { ipaddr = "127.0.0.1" }, "pubsub", ["$SYS/#", "#"]],        # 允许 IP 地址为 "127.0.0.1" 的客户端发布/订阅 "$SYS/#"，"#" 主题
    ["deny", "all", "subscribe", ["$SYS/#", { eq = "#" }]],                # 拒绝 "所有用户" 订阅 "$SYS/#" "#" 主题

	["allow", { user = "dashboard", password = "123456" }, "connect"],     # 允许用户名为:dashboard，密码为:123456 的客户端连接请求
    ["allow", { user = "admin", password = "123456", superuser = true }],  # 允许用户名为:admin，密码为:123456 的客户端连接请求并设置为超级用户
	["allow", { user = "test", password = "123456" }, "connect"],          # 允许用户名为:test，密码为:123456 的客户端连接请求
    ["allow", { user = "test1", password = "123456" }, "connect"],         # 允许用户名为:test1，密码为:123456 的客户端连接请求
    ["allow", { user = "test2", password = "123456" }, "connect"],         # 允许用户名为:test2，密码为:123456 的客户端连接请求
    ["allow", { user = "test3", password = "123456" }, "connect"],         # 允许用户名为:test3，密码为:123456 的客户端连接请求
	
	["allow", { user = "test" }, "subscribe", ["test/#"]],                 # 允许用户名为test的客户端订阅"test/#"主题
    ["allow", { user = "test1" }, "publish", ["test/1"]],                  # 允许用户名为test1的客户端订阅"test/1"主题
    ["allow", { user = "test2" }, "publish", ["test/2"]],                  # 允许用户名为test2的客户端订阅"test/2"主题
    ["allow", { user = "test3" }, "publish", ["test/3"]],                  # 允许用户名为test3的客户端订阅"test/3"主题
	
    ["deny", "all"] #拒绝其它所有操作，包括连接、发布、订阅
]

