##--------------------------------------------------------------------
## rmqtt-acl
##--------------------------------------------------------------------

#Disconnect if publishing is rejected
disconnect_if_pub_rejected = true

rules = [
    ["allow", { user = "dashboard" }, "subscribe", ["$SYS/#"]],
    ["allow", { ipaddr = "127.0.0.1" }, "pubsub", ["$SYS/#", "#"]],
    ["deny", "all", "subscribe", ["$SYS/#", { eq = "#" }]],

    ["allow", { user = "admin", password = "123456", superuser = true }, "connect"],
    ["allow", { user = "test1", password = "123456" }],
    ["allow", { user = "test2", password = "123456" }],
    ["allow", { user = "test3", password = "123456" }],

    ["deny", "all"]
]

